-- Deska News slim architecture: remove ERP modules, keep platform + smart publishing

DROP TABLE IF EXISTS "DailyReportItem" CASCADE;
DROP TABLE IF EXISTS "DailyReportArticleDecision" CASCADE;
DROP TABLE IF EXISTS "DailyReport" CASCADE;

DROP TABLE IF EXISTS "EventManagementBudgetItem" CASCADE;
DROP TABLE IF EXISTS "EventManagementAgendaItem" CASCADE;
DROP TABLE IF EXISTS "EventManagementTask" CASCADE;
DROP TABLE IF EXISTS "EventManagementProject" CASCADE;

DROP TABLE IF EXISTS "ApprovalStep" CASCADE;
DROP TABLE IF EXISTS "ChecklistItem" CASCADE;
DROP TABLE IF EXISTS "ProjectMember" CASCADE;
DROP TABLE IF EXISTS "Task" CASCADE;
DROP TABLE IF EXISTS "Project" CASCADE;

DROP TABLE IF EXISTS "PublishArticle" CASCADE;
DROP TABLE IF EXISTS "PublishChannel" CASCADE;
DROP TABLE IF EXISTS "SocialFeed" CASCADE;

DROP TABLE IF EXISTS "Applicant" CASCADE;
DROP TABLE IF EXISTS "JobOpening" CASCADE;
DROP TABLE IF EXISTS "Employee" CASCADE;
DROP TABLE IF EXISTS "Department" CASCADE;

DROP TABLE IF EXISTS "CalendarEventAttendee" CASCADE;
DROP TABLE IF EXISTS "CalendarEvent" CASCADE;
DROP TABLE IF EXISTS "SystemCalendarObservance" CASCADE;

DROP TABLE IF EXISTS "DocumentFile" CASCADE;
DROP TABLE IF EXISTS "DocumentFolder" CASCADE;
DROP TABLE IF EXISTS "ContactBankAccount" CASCADE;
DROP TABLE IF EXISTS "Contact" CASCADE;

DROP TABLE IF EXISTS "CustomFieldValue" CASCADE;
DROP TABLE IF EXISTS "CustomFieldDefinition" CASCADE;
DROP TABLE IF EXISTS "NumberSequence" CASCADE;

DROP TABLE IF EXISTS "TenantModule" CASCADE;
DROP TABLE IF EXISTS "ModuleDefinition" CASCADE;
