-- AlterTable
ALTER TABLE "PlatformFeed" ADD COLUMN IF NOT EXISTS "healthStatus" TEXT NOT NULL DEFAULT 'unknown';
ALTER TABLE "PlatformFeed" ADD COLUMN IF NOT EXISTS "healthCheckedAt" TIMESTAMP(3);
ALTER TABLE "PlatformFeed" ADD COLUMN IF NOT EXISTS "healthItemCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "PlatformFeed" ADD COLUMN IF NOT EXISTS "healthError" TEXT NOT NULL DEFAULT '';
ALTER TABLE "PlatformFeed" ADD COLUMN IF NOT EXISTS "healthFailSince" TIMESTAMP(3);
