/** مشخصات ماژول‌های هسته DESKA ERP */
export interface EntityFieldSpec { name: string; label: string; type: 'text'|'email'|'phone'|'number'|'date'|'select'|'textarea'|'boolean'|'relation'; required?: boolean; relation?: { moduleId: string; entity: string; field: string }; options?: { value: string; label: string }[]; }
export interface EntitySpec { id: string; label: string; apiPath: string; fields: EntityFieldSpec[]; }
export interface NavItemSpec { href: string; label: string; moduleId: string; }
export interface CoreModuleSpec { id: string; name: string; domain: string; description: string; dependencies: string[]; isCore?: boolean; entities: EntitySpec[]; navItems: NavItemSpec[]; relations: string[]; }
export const CORE_MODULE_IDS = ['contacts', 'documents', 'calendar', 'employees'] as const;
export type CoreModuleId = (typeof CORE_MODULE_IDS)[number];
export const ALWAYS_ENABLED_MODULE_IDS: readonly string[] = [];
export const CORE_MODULE_SPECS: CoreModuleSpec[] = [
  { id: 'contacts', name: 'مخاطبین', domain: 'platform', description: 'مخاطبان حقیقی و حقوقی سازمان', dependencies: [], isCore: true, entities: [{ id: 'Contact', label: 'مخاطب', apiPath: '/contacts', fields: [{ name: 'type', label: 'نوع', type: 'select', required: true }, { name: 'firstName', label: 'نام', type: 'text' }, { name: 'lastName', label: 'نام خانوادگی', type: 'text' }, { name: 'companyName', label: 'نام شرکت', type: 'text' }, { name: 'email', label: 'ایمیل', type: 'email' }, { name: 'mobile', label: 'موبایل', type: 'phone' }] }], navItems: [{ href: '/contacts', label: 'مخاطبین', moduleId: 'contacts' }], relations: ['employees'] },
  { id: 'documents', name: 'اسناد', domain: 'productivity', description: 'مدیریت فایل‌ها و پوشه‌های سازمان', dependencies: [], isCore: true, entities: [{ id: 'DocumentFile', label: 'فایل', apiPath: '/documents/files', fields: [{ name: 'originalName', label: 'نام فایل', type: 'text', required: true }] }], navItems: [{ href: '/documents', label: 'اسناد', moduleId: 'documents' }], relations: ['*.entityType'] },
  { id: 'calendar', name: 'تقویم', domain: 'productivity', description: 'رویدادها و مناسبت‌ها', dependencies: [], isCore: true, entities: [{ id: 'CalendarEvent', label: 'رویداد', apiPath: '/calendar/events', fields: [{ name: 'title', label: 'عنوان', type: 'text', required: true }, { name: 'startAt', label: 'شروع', type: 'date', required: true }, { name: 'endAt', label: 'پایان', type: 'date', required: true }] }], navItems: [{ href: '/calendar', label: 'تقویم', moduleId: 'calendar' }], relations: ['*.entityType'] },
  { id: 'employees', name: 'کارمندان', domain: 'platform', description: 'پرونده‌های پرسنلی و اعضای سازمان', dependencies: [], isCore: true, entities: [{ id: 'Employee', label: 'کارمند', apiPath: '/employees', fields: [{ name: 'employeeCode', label: 'کد پرسنلی', type: 'text', required: true }, { name: 'jobTitle', label: 'سمت', type: 'text' }, { name: 'hireDate', label: 'تاریخ استخدام', type: 'date' }] }], navItems: [{ href: '/employees', label: 'کارمندان', moduleId: 'employees' }], relations: ['contacts'] },
];
export function getCoreModuleSpec(moduleId: string): CoreModuleSpec | undefined { return CORE_MODULE_SPECS.find((module) => module.id === moduleId); }
