import type { FeedCatalogGroup } from './feed-catalog-groups';
import type { FeedSourceType } from './feed-source-types';
import type { SourceLanguage } from './source-language';

export type DefaultPlatformFeedSeed = {
  name: string;
  url: string;
  sourceType: FeedSourceType;
  catalogGroup: FeedCatalogGroup;
  sourceLanguage: SourceLanguage;
  pollIntervalMinutes: number;
};

/** Bump when the default catalog composition changes and existing DB rows must be wiped. */
export const PLATFORM_FEED_CATALOG_VERSION = 5;

/**
 * کاتالوگ curated v5 برای برنا (borna.news).
 * فقط منابع بالاسری؛ رسانه‌های دولتی/عمومی کشورهای مهم؛ orgs-companies برای منبع اولیه سازمانی.
 */
export const DEFAULT_PLATFORM_FEEDS: DefaultPlatformFeedSeed[] = [
  // —— media-domestic / fa (۳۰) ——
  { name: 'خبرگزاری مهر', url: 'https://www.mehrnews.com/rss', sourceType: 'rss', catalogGroup: 'media-domestic', sourceLanguage: 'fa', pollIntervalMinutes: 240 },
  { name: 'خبرگزاری ایسنا', url: 'https://www.isna.ir/rss', sourceType: 'rss', catalogGroup: 'media-domestic', sourceLanguage: 'fa', pollIntervalMinutes: 240 },
  { name: 'خبرگزاری ایرنا', url: 'https://www.irna.ir/rss', sourceType: 'rss', catalogGroup: 'media-domestic', sourceLanguage: 'fa', pollIntervalMinutes: 240 },
  { name: 'خبرگزاری تسنیم', url: 'https://www.tasnimnews.com', sourceType: 'website', catalogGroup: 'media-domestic', sourceLanguage: 'fa', pollIntervalMinutes: 240 },
  { name: 'خبرگزاری فارس', url: 'https://www.farsnews.ir', sourceType: 'website', catalogGroup: 'media-domestic', sourceLanguage: 'fa', pollIntervalMinutes: 240 },
  { name: 'خبرگزاری ایلنا', url: 'https://www.ilna.ir/rss', sourceType: 'rss', catalogGroup: 'media-domestic', sourceLanguage: 'fa', pollIntervalMinutes: 240 },
  { name: 'خبرگزاری دانشجو', url: 'https://snn.ir', sourceType: 'website', catalogGroup: 'media-domestic', sourceLanguage: 'fa', pollIntervalMinutes: 240 },
  { name: 'باشگاه خبرنگاران جوان', url: 'https://www.yjc.ir', sourceType: 'website', catalogGroup: 'media-domestic', sourceLanguage: 'fa', pollIntervalMinutes: 240 },
  { name: 'انتخاب', url: 'https://www.entekhab.ir/fa/rss/allnews', sourceType: 'rss', catalogGroup: 'media-domestic', sourceLanguage: 'fa', pollIntervalMinutes: 240 },
  { name: 'تابناک', url: 'https://www.tabnak.ir/fa/rss/allnews', sourceType: 'rss', catalogGroup: 'media-domestic', sourceLanguage: 'fa', pollIntervalMinutes: 240 },
  { name: 'همشهری آنلاین', url: 'https://www.hamshahrionline.ir/rss', sourceType: 'rss', catalogGroup: 'media-domestic', sourceLanguage: 'fa', pollIntervalMinutes: 240 },
  { name: 'خبرآنلاین', url: 'https://www.khabaronline.ir/rss', sourceType: 'rss', catalogGroup: 'media-domestic', sourceLanguage: 'fa', pollIntervalMinutes: 240 },
  { name: 'دنیای اقتصاد', url: 'https://www.donya-e-eqtesad.com', sourceType: 'website', catalogGroup: 'media-domestic', sourceLanguage: 'fa', pollIntervalMinutes: 240 },
  { name: 'اقتصادنیوز', url: 'https://www.eghtesadnews.com', sourceType: 'website', catalogGroup: 'media-domestic', sourceLanguage: 'fa', pollIntervalMinutes: 240 },
  { name: 'تجارت‌نیوز', url: 'https://tejaratnews.com', sourceType: 'website', catalogGroup: 'media-domestic', sourceLanguage: 'fa', pollIntervalMinutes: 240 },
  { name: 'فرارو', url: 'https://fararu.com', sourceType: 'website', catalogGroup: 'media-domestic', sourceLanguage: 'fa', pollIntervalMinutes: 240 },
  { name: 'عصر ایران', url: 'https://www.asriran.com', sourceType: 'website', catalogGroup: 'media-domestic', sourceLanguage: 'fa', pollIntervalMinutes: 240 },
  { name: 'خبر ورزشی', url: 'https://www.khabarvarzeshi.com', sourceType: 'website', catalogGroup: 'media-domestic', sourceLanguage: 'fa', pollIntervalMinutes: 240 },
  { name: 'ورزش۳', url: 'https://www.varzesh3.com/rss', sourceType: 'rss', catalogGroup: 'media-domestic', sourceLanguage: 'fa', pollIntervalMinutes: 240 },
  { name: 'طرفداری', url: 'https://www.tarafdari.com', sourceType: 'website', catalogGroup: 'media-domestic', sourceLanguage: 'fa', pollIntervalMinutes: 240 },
  { name: 'فوتبال۳۶۰', url: 'https://www.football360.ir', sourceType: 'website', catalogGroup: 'media-domestic', sourceLanguage: 'fa', pollIntervalMinutes: 240 },
  { name: 'آی‌اسپورت', url: 'https://www.isport.ir', sourceType: 'website', catalogGroup: 'media-domestic', sourceLanguage: 'fa', pollIntervalMinutes: 240 },
  { name: 'متافوتبال', url: 'https://www.metafutbol.com', sourceType: 'website', catalogGroup: 'media-domestic', sourceLanguage: 'fa', pollIntervalMinutes: 240 },
  { name: 'دیجیاتو', url: 'https://digiato.com', sourceType: 'website', catalogGroup: 'media-domestic', sourceLanguage: 'fa', pollIntervalMinutes: 240 },
  { name: 'زومیت', url: 'https://www.zoomit.ir', sourceType: 'website', catalogGroup: 'media-domestic', sourceLanguage: 'fa', pollIntervalMinutes: 240 },
  { name: 'پیوست', url: 'https://peivast.com', sourceType: 'website', catalogGroup: 'media-domestic', sourceLanguage: 'fa', pollIntervalMinutes: 240 },
  { name: 'خبرگزاری پانا', url: 'https://www.pana.ir', sourceType: 'website', catalogGroup: 'media-domestic', sourceLanguage: 'fa', pollIntervalMinutes: 240 },
  { name: 'خبرگزاری شبستان', url: 'https://www.shabestan.ir', sourceType: 'website', catalogGroup: 'media-domestic', sourceLanguage: 'fa', pollIntervalMinutes: 240 },
  { name: 'خبرگزاری رضوی', url: 'https://www.razavi.news', sourceType: 'website', catalogGroup: 'media-domestic', sourceLanguage: 'fa', pollIntervalMinutes: 240 },
  { name: 'اکوایران', url: 'https://ecoiran.com', sourceType: 'website', catalogGroup: 'media-domestic', sourceLanguage: 'fa', pollIntervalMinutes: 240 },

  // —— media-international (۳۲) ——
  { name: 'BBC News', url: 'https://feeds.bbci.co.uk/news/world/rss.xml', sourceType: 'rss', catalogGroup: 'media-international', sourceLanguage: 'en', pollIntervalMinutes: 360 },
  { name: 'Reuters', url: 'https://www.reuters.com', sourceType: 'website', catalogGroup: 'media-international', sourceLanguage: 'en', pollIntervalMinutes: 360 },
  { name: 'Associated Press', url: 'https://apnews.com', sourceType: 'website', catalogGroup: 'media-international', sourceLanguage: 'en', pollIntervalMinutes: 360 },
  { name: 'The Guardian', url: 'https://www.theguardian.com/world/rss', sourceType: 'rss', catalogGroup: 'media-international', sourceLanguage: 'en', pollIntervalMinutes: 360 },
  { name: 'CNN', url: 'https://edition.cnn.com', sourceType: 'website', catalogGroup: 'media-international', sourceLanguage: 'en', pollIntervalMinutes: 360 },
  { name: 'AFP', url: 'https://www.afp.com', sourceType: 'website', catalogGroup: 'media-international', sourceLanguage: 'en', pollIntervalMinutes: 360 },
  { name: 'France 24', url: 'https://www.france24.com/en/', sourceType: 'website', catalogGroup: 'media-international', sourceLanguage: 'en', pollIntervalMinutes: 360 },
  { name: 'Tagesschau', url: 'https://www.tagesschau.de/xml/rss2', sourceType: 'rss', catalogGroup: 'media-international', sourceLanguage: 'de', pollIntervalMinutes: 360 },
  { name: 'Der Spiegel', url: 'https://www.spiegel.de/schlagzeilen/index.rss', sourceType: 'rss', catalogGroup: 'media-international', sourceLanguage: 'de', pollIntervalMinutes: 360 },
  { name: 'FAZ', url: 'https://www.faz.net/rss/aktuell/', sourceType: 'rss', catalogGroup: 'media-international', sourceLanguage: 'de', pollIntervalMinutes: 360 },
  { name: 'Le Monde', url: 'https://www.lemonde.fr/international/rss_full.xml', sourceType: 'rss', catalogGroup: 'media-international', sourceLanguage: 'fr', pollIntervalMinutes: 360 },
  { name: 'Le Figaro', url: 'https://www.lefigaro.fr/rss/figaro_international.xml', sourceType: 'rss', catalogGroup: 'media-international', sourceLanguage: 'fr', pollIntervalMinutes: 360 },
  { name: 'EFE', url: 'https://efe.com', sourceType: 'website', catalogGroup: 'media-international', sourceLanguage: 'en', pollIntervalMinutes: 360 },
  { name: 'ANSA', url: 'https://www.ansa.it', sourceType: 'website', catalogGroup: 'media-international', sourceLanguage: 'en', pollIntervalMinutes: 360 },
  { name: 'الجزیره', url: 'https://www.aljazeera.net/aljazeerarss', sourceType: 'rss', catalogGroup: 'media-international', sourceLanguage: 'ar', pollIntervalMinutes: 360 },
  { name: 'العربية', url: 'https://www.alarabiya.net', sourceType: 'website', catalogGroup: 'media-international', sourceLanguage: 'ar', pollIntervalMinutes: 360 },
  { name: 'وكالة الأنباء السعودية — SPA', url: 'https://www.spa.gov.sa', sourceType: 'website', catalogGroup: 'media-international', sourceLanguage: 'ar', pollIntervalMinutes: 360 },
  { name: 'وام — WAM', url: 'https://www.wam.ae', sourceType: 'website', catalogGroup: 'media-international', sourceLanguage: 'ar', pollIntervalMinutes: 360 },
  { name: 'الأهرام', url: 'https://www.ahram.org.eg', sourceType: 'website', catalogGroup: 'media-international', sourceLanguage: 'ar', pollIntervalMinutes: 360 },
  { name: 'آژانس آنادولو — عربی', url: 'https://www.aa.com.tr/ar/rss/default?cat=guncel', sourceType: 'rss', catalogGroup: 'media-international', sourceLanguage: 'ar', pollIntervalMinutes: 360 },
  { name: 'Anadolu Ajansı', url: 'https://www.aa.com.tr/tr/rss/default?cat=guncel', sourceType: 'rss', catalogGroup: 'media-international', sourceLanguage: 'tr', pollIntervalMinutes: 360 },
  { name: 'TRT Haber', url: 'https://www.trthaber.com/sondakika.rss', sourceType: 'rss', catalogGroup: 'media-international', sourceLanguage: 'tr', pollIntervalMinutes: 360 },
  { name: 'Hürriyet', url: 'https://www.hurriyet.com.tr/rss/gundem', sourceType: 'rss', catalogGroup: 'media-international', sourceLanguage: 'tr', pollIntervalMinutes: 360 },
  { name: 'TASS', url: 'https://tass.com', sourceType: 'website', catalogGroup: 'media-international', sourceLanguage: 'en', pollIntervalMinutes: 360 },
  { name: 'RIA Novosti', url: 'https://ria.ru', sourceType: 'website', catalogGroup: 'media-international', sourceLanguage: 'en', pollIntervalMinutes: 360 },
  { name: '新华社', url: 'https://www.news.cn', sourceType: 'website', catalogGroup: 'media-international', sourceLanguage: 'zh', pollIntervalMinutes: 360 },
  { name: '人民网', url: 'https://www.people.com.cn/rss/politics.xml', sourceType: 'rss', catalogGroup: 'media-international', sourceLanguage: 'zh', pollIntervalMinutes: 360 },
  { name: 'CGTN', url: 'https://www.cgtn.com', sourceType: 'website', catalogGroup: 'media-international', sourceLanguage: 'en', pollIntervalMinutes: 360 },
  { name: 'NHK', url: 'https://www3.nhk.or.jp/rss/news/cat0.xml', sourceType: 'rss', catalogGroup: 'media-international', sourceLanguage: 'ja', pollIntervalMinutes: 360 },
  { name: 'PTI', url: 'https://www.ptinews.com', sourceType: 'website', catalogGroup: 'media-international', sourceLanguage: 'en', pollIntervalMinutes: 360 },
  { name: 'Ynet', url: 'https://www.ynet.co.il/Integration/StoryRss2.xml', sourceType: 'rss', catalogGroup: 'media-international', sourceLanguage: 'he', pollIntervalMinutes: 360 },
  { name: 'Olympics.com', url: 'https://www.olympics.com', sourceType: 'website', catalogGroup: 'media-international', sourceLanguage: 'en', pollIntervalMinutes: 360 },

  // —— telegram / fa (۳۰) ——
  { name: 'وحید آنلاین', url: 'https://t.me/VahidOnline', sourceType: 'telegram', catalogGroup: 'telegram', sourceLanguage: 'fa', pollIntervalMinutes: 180 },
  { name: 'جریان', url: 'https://t.me/jaryanews', sourceType: 'telegram', catalogGroup: 'telegram', sourceLanguage: 'fa', pollIntervalMinutes: 180 },
  { name: 'خبرفوری', url: 'https://t.me/khabarfori', sourceType: 'telegram', catalogGroup: 'telegram', sourceLanguage: 'fa', pollIntervalMinutes: 180 },
  { name: 'تیتر اول', url: 'https://t.me/titraval', sourceType: 'telegram', catalogGroup: 'telegram', sourceLanguage: 'fa', pollIntervalMinutes: 180 },
  { name: 'دیجیاتو', url: 'https://t.me/digiato', sourceType: 'telegram', catalogGroup: 'telegram', sourceLanguage: 'fa', pollIntervalMinutes: 180 },
  { name: 'زومیت', url: 'https://t.me/Zoomit', sourceType: 'telegram', catalogGroup: 'telegram', sourceLanguage: 'fa', pollIntervalMinutes: 180 },
  { name: 'بازتاب', url: 'https://t.me/baztab_ir', sourceType: 'telegram', catalogGroup: 'telegram', sourceLanguage: 'fa', pollIntervalMinutes: 180 },
  { name: 'پنجشنبه', url: 'https://t.me/panjeshe', sourceType: 'telegram', catalogGroup: 'telegram', sourceLanguage: 'fa', pollIntervalMinutes: 180 },
  { name: 'طرفداری', url: 'https://t.me/Tarafdari', sourceType: 'telegram', catalogGroup: 'telegram', sourceLanguage: 'fa', pollIntervalMinutes: 180 },
  { name: 'ورزش۳', url: 'https://t.me/varzesh3', sourceType: 'telegram', catalogGroup: 'telegram', sourceLanguage: 'fa', pollIntervalMinutes: 180 },
  { name: 'فوتبال۳۶۰', url: 'https://t.me/football360', sourceType: 'telegram', catalogGroup: 'telegram', sourceLanguage: 'fa', pollIntervalMinutes: 180 },
  { name: 'گجت‌نیوز', url: 'https://t.me/gadgetnews', sourceType: 'telegram', catalogGroup: 'telegram', sourceLanguage: 'fa', pollIntervalMinutes: 180 },
  { name: 'یک پزشک', url: 'https://t.me/yekpezeshk', sourceType: 'telegram', catalogGroup: 'telegram', sourceLanguage: 'fa', pollIntervalMinutes: 180 },
  { name: 'انصاف‌نیوز', url: 'https://t.me/ensafnews', sourceType: 'telegram', catalogGroup: 'telegram', sourceLanguage: 'fa', pollIntervalMinutes: 180 },
  { name: 'دیده‌بان ایران', url: 'https://t.me/didbaniran', sourceType: 'telegram', catalogGroup: 'telegram', sourceLanguage: 'fa', pollIntervalMinutes: 180 },
  { name: 'اکوایران', url: 'https://t.me/ecoiran', sourceType: 'telegram', catalogGroup: 'telegram', sourceLanguage: 'fa', pollIntervalMinutes: 180 },
  { name: 'پیوست', url: 'https://t.me/peivast', sourceType: 'telegram', catalogGroup: 'telegram', sourceLanguage: 'fa', pollIntervalMinutes: 180 },
  { name: 'آی‌تی ایران', url: 'https://t.me/itirancom', sourceType: 'telegram', catalogGroup: 'telegram', sourceLanguage: 'fa', pollIntervalMinutes: 180 },
  { name: 'مدالیته', url: 'https://t.me/modality_ir', sourceType: 'telegram', catalogGroup: 'telegram', sourceLanguage: 'fa', pollIntervalMinutes: 180 },
  { name: 'سینماپرس', url: 'https://t.me/cinemapress', sourceType: 'telegram', catalogGroup: 'telegram', sourceLanguage: 'fa', pollIntervalMinutes: 180 },
  { name: 'استارتاپ‌نیوز', url: 'https://t.me/startupnews_ir', sourceType: 'telegram', catalogGroup: 'telegram', sourceLanguage: 'fa', pollIntervalMinutes: 180 },
  { name: 'کاراگاه ورزشی', url: 'https://t.me/karagah_varzeshi', sourceType: 'telegram', catalogGroup: 'telegram', sourceLanguage: 'fa', pollIntervalMinutes: 180 },
  { name: 'نقل ورزشی', url: 'https://t.me/naghlevarzeshi', sourceType: 'telegram', catalogGroup: 'telegram', sourceLanguage: 'fa', pollIntervalMinutes: 180 },
  { name: 'صبحانه با خبرنگاران', url: 'https://t.me/sobhaneh_ba_khabarnegaran', sourceType: 'telegram', catalogGroup: 'telegram', sourceLanguage: 'fa', pollIntervalMinutes: 180 },
  { name: 'دانشگاه‌خبر', url: 'https://t.me/daneshgahnews', sourceType: 'telegram', catalogGroup: 'telegram', sourceLanguage: 'fa', pollIntervalMinutes: 180 },
  { name: 'تجارت‌نیوز', url: 'https://t.me/tejaratnews', sourceType: 'telegram', catalogGroup: 'telegram', sourceLanguage: 'fa', pollIntervalMinutes: 180 },
  { name: 'فرارو', url: 'https://t.me/fararunews', sourceType: 'telegram', catalogGroup: 'telegram', sourceLanguage: 'fa', pollIntervalMinutes: 180 },
  { name: 'عصر ایران', url: 'https://t.me/asriran_com', sourceType: 'telegram', catalogGroup: 'telegram', sourceLanguage: 'fa', pollIntervalMinutes: 180 },
  { name: 'دیجیاتو تک', url: 'https://t.me/digiatotech', sourceType: 'telegram', catalogGroup: 'telegram', sourceLanguage: 'fa', pollIntervalMinutes: 180 },
  { name: 'آی‌فیلم', url: 'https://t.me/ifilm_ir', sourceType: 'telegram', catalogGroup: 'telegram', sourceLanguage: 'fa', pollIntervalMinutes: 180 },

  // —— twitter (۳۲) ——
  { name: 'آیت‌الله خامنه‌ای', url: 'https://x.com/khamenei_ir', sourceType: 'twitter', catalogGroup: 'twitter', sourceLanguage: 'fa', pollIntervalMinutes: 180 },
  { name: 'مسعود پزشکیان', url: 'https://x.com/drpezeshkian', sourceType: 'twitter', catalogGroup: 'twitter', sourceLanguage: 'fa', pollIntervalMinutes: 180 },
  { name: 'عباس عراقچی', url: 'https://x.com/araghchi', sourceType: 'twitter', catalogGroup: 'twitter', sourceLanguage: 'fa', pollIntervalMinutes: 180 },
  { name: 'وزارت خارجه ایران', url: 'https://x.com/IRIMFA_EN', sourceType: 'twitter', catalogGroup: 'twitter', sourceLanguage: 'en', pollIntervalMinutes: 180 },
  { name: 'احمد دنیامالی', url: 'https://x.com/ADonyamali', sourceType: 'twitter', catalogGroup: 'twitter', sourceLanguage: 'fa', pollIntervalMinutes: 180 },
  { name: 'کمیته ملی المپیک ایران', url: 'https://x.com/nociri', sourceType: 'twitter', catalogGroup: 'twitter', sourceLanguage: 'fa', pollIntervalMinutes: 180 },
  { name: 'فدراسیون فوتبال ایران', url: 'https://x.com/ffiri_media', sourceType: 'twitter', catalogGroup: 'twitter', sourceLanguage: 'fa', pollIntervalMinutes: 180 },
  { name: 'تیم ملی فوتبال ایران', url: 'https://x.com/TeamMelli', sourceType: 'twitter', catalogGroup: 'twitter', sourceLanguage: 'fa', pollIntervalMinutes: 180 },
  { name: 'POTUS', url: 'https://x.com/POTUS', sourceType: 'twitter', catalogGroup: 'twitter', sourceLanguage: 'en', pollIntervalMinutes: 180 },
  { name: 'Emmanuel Macron', url: 'https://x.com/EmmanuelMacron', sourceType: 'twitter', catalogGroup: 'twitter', sourceLanguage: 'fr', pollIntervalMinutes: 180 },
  { name: 'Netanyahu', url: 'https://x.com/netanyahu', sourceType: 'twitter', catalogGroup: 'twitter', sourceLanguage: 'en', pollIntervalMinutes: 180 },
  { name: 'Antonio Guterres', url: 'https://x.com/AntonioGuterres', sourceType: 'twitter', catalogGroup: 'twitter', sourceLanguage: 'en', pollIntervalMinutes: 180 },
  { name: 'Ursula von der Leyen', url: 'https://x.com/vonderleyen', sourceType: 'twitter', catalogGroup: 'twitter', sourceLanguage: 'en', pollIntervalMinutes: 180 },
  { name: 'Narendra Modi', url: 'https://x.com/narendramodi', sourceType: 'twitter', catalogGroup: 'twitter', sourceLanguage: 'en', pollIntervalMinutes: 180 },
  { name: 'Volodymyr Zelenskyy', url: 'https://x.com/ZelenskyyUa', sourceType: 'twitter', catalogGroup: 'twitter', sourceLanguage: 'en', pollIntervalMinutes: 180 },
  { name: 'IOC Media', url: 'https://x.com/iocmedia', sourceType: 'twitter', catalogGroup: 'twitter', sourceLanguage: 'en', pollIntervalMinutes: 180 },
  { name: 'FIFA', url: 'https://x.com/FIFAcom', sourceType: 'twitter', catalogGroup: 'twitter', sourceLanguage: 'en', pollIntervalMinutes: 180 },
  { name: 'UEFA', url: 'https://x.com/UEFA', sourceType: 'twitter', catalogGroup: 'twitter', sourceLanguage: 'en', pollIntervalMinutes: 180 },
  { name: 'Olympics', url: 'https://x.com/Olympics', sourceType: 'twitter', catalogGroup: 'twitter', sourceLanguage: 'en', pollIntervalMinutes: 180 },
  { name: 'Xinhua News', url: 'https://x.com/XHNews', sourceType: 'twitter', catalogGroup: 'twitter', sourceLanguage: 'en', pollIntervalMinutes: 180 },
  { name: 'CGTN', url: 'https://x.com/CGTNOfficial', sourceType: 'twitter', catalogGroup: 'twitter', sourceLanguage: 'en', pollIntervalMinutes: 180 },
  { name: 'TASS', url: 'https://x.com/tass_agency', sourceType: 'twitter', catalogGroup: 'twitter', sourceLanguage: 'en', pollIntervalMinutes: 180 },
  { name: 'Anadolu Agency', url: 'https://x.com/anadoluagency', sourceType: 'twitter', catalogGroup: 'twitter', sourceLanguage: 'en', pollIntervalMinutes: 180 },
  { name: 'SPA', url: 'https://x.com/SPAregions', sourceType: 'twitter', catalogGroup: 'twitter', sourceLanguage: 'en', pollIntervalMinutes: 180 },
  { name: 'WAM UAE', url: 'https://x.com/wamnews', sourceType: 'twitter', catalogGroup: 'twitter', sourceLanguage: 'en', pollIntervalMinutes: 180 },
  { name: 'Al Jazeera English', url: 'https://x.com/AJEnglish', sourceType: 'twitter', catalogGroup: 'twitter', sourceLanguage: 'en', pollIntervalMinutes: 180 },
  { name: 'الجزیره', url: 'https://x.com/AJArabic', sourceType: 'twitter', catalogGroup: 'twitter', sourceLanguage: 'ar', pollIntervalMinutes: 180 },
  { name: 'Farnaz Fassihi', url: 'https://x.com/farnazfassihi', sourceType: 'twitter', catalogGroup: 'twitter', sourceLanguage: 'en', pollIntervalMinutes: 180 },
  { name: 'Ali Vaez', url: 'https://x.com/alivaez', sourceType: 'twitter', catalogGroup: 'twitter', sourceLanguage: 'en', pollIntervalMinutes: 180 },
  { name: 'Hadi Nili', url: 'https://x.com/HadiNili', sourceType: 'twitter', catalogGroup: 'twitter', sourceLanguage: 'fa', pollIntervalMinutes: 180 },
  { name: 'TRT World', url: 'https://x.com/trtworld', sourceType: 'twitter', catalogGroup: 'twitter', sourceLanguage: 'en', pollIntervalMinutes: 180 },
  { name: 'Reuters', url: 'https://x.com/Reuters', sourceType: 'twitter', catalogGroup: 'twitter', sourceLanguage: 'en', pollIntervalMinutes: 180 },

  // —— orgs-companies (۳۱) ——
  { name: 'وزارت ورزش و جوانان', url: 'https://www.msy.gov.ir', sourceType: 'website', catalogGroup: 'orgs-companies', sourceLanguage: 'fa', pollIntervalMinutes: 360 },
  { name: 'کمیته ملی المپیک', url: 'https://www.olympic.ir', sourceType: 'website', catalogGroup: 'orgs-companies', sourceLanguage: 'fa', pollIntervalMinutes: 360 },
  { name: 'کمیته ملی پارالمپیک', url: 'https://www.paralympic.ir', sourceType: 'website', catalogGroup: 'orgs-companies', sourceLanguage: 'fa', pollIntervalMinutes: 360 },
  { name: 'فدراسیون فوتبال ایران', url: 'https://www.ffiri.ir', sourceType: 'website', catalogGroup: 'orgs-companies', sourceLanguage: 'fa', pollIntervalMinutes: 360 },
  { name: 'سازمان لیگ فوتبال', url: 'https://www.iranleague.ir', sourceType: 'website', catalogGroup: 'orgs-companies', sourceLanguage: 'fa', pollIntervalMinutes: 360 },
  { name: 'فدراسیون والیبال', url: 'https://www.volleyball.ir', sourceType: 'website', catalogGroup: 'orgs-companies', sourceLanguage: 'fa', pollIntervalMinutes: 360 },
  { name: 'فدراسیون بسکتبال', url: 'https://www.iranbasketball.org', sourceType: 'website', catalogGroup: 'orgs-companies', sourceLanguage: 'fa', pollIntervalMinutes: 360 },
  { name: 'فدراسیون کشتی', url: 'https://www.iwf.ir', sourceType: 'website', catalogGroup: 'orgs-companies', sourceLanguage: 'fa', pollIntervalMinutes: 360 },
  { name: 'فدراسیون وزنه‌برداری', url: 'https://www.iwrf.ir', sourceType: 'website', catalogGroup: 'orgs-companies', sourceLanguage: 'fa', pollIntervalMinutes: 360 },
  { name: 'فدراسیون تکواندو', url: 'https://www.itifed.ir', sourceType: 'website', catalogGroup: 'orgs-companies', sourceLanguage: 'fa', pollIntervalMinutes: 360 },
  { name: 'وزارت علوم', url: 'https://www.msrt.ir', sourceType: 'website', catalogGroup: 'orgs-companies', sourceLanguage: 'fa', pollIntervalMinutes: 360 },
  { name: 'وزارت آموزش و پرورش', url: 'https://www.medu.ir', sourceType: 'website', catalogGroup: 'orgs-companies', sourceLanguage: 'fa', pollIntervalMinutes: 360 },
  { name: 'معاونت علمی ریاست‌جمهوری', url: 'https://www.isti.ir', sourceType: 'website', catalogGroup: 'orgs-companies', sourceLanguage: 'fa', pollIntervalMinutes: 360 },
  { name: 'سازمان فناوری اطلاعات', url: 'https://www.ito.gov.ir', sourceType: 'website', catalogGroup: 'orgs-companies', sourceLanguage: 'fa', pollIntervalMinutes: 360 },
  { name: 'سازمان بورس', url: 'https://www.seo.ir', sourceType: 'website', catalogGroup: 'orgs-companies', sourceLanguage: 'fa', pollIntervalMinutes: 360 },
  { name: 'اتاق بازرگانی ایران', url: 'https://www.iccima.ir', sourceType: 'website', catalogGroup: 'orgs-companies', sourceLanguage: 'fa', pollIntervalMinutes: 360 },
  { name: 'سازمان ملل — News', url: 'https://news.un.org', sourceType: 'website', catalogGroup: 'orgs-companies', sourceLanguage: 'en', pollIntervalMinutes: 360 },
  { name: 'UNESCO Newsroom', url: 'https://www.unesco.org/en/newsroom', sourceType: 'website', catalogGroup: 'orgs-companies', sourceLanguage: 'en', pollIntervalMinutes: 360 },
  { name: 'WHO News', url: 'https://www.who.int/news', sourceType: 'website', catalogGroup: 'orgs-companies', sourceLanguage: 'en', pollIntervalMinutes: 360 },
  { name: 'IOC', url: 'https://www.olympics.com/ioc', sourceType: 'website', catalogGroup: 'orgs-companies', sourceLanguage: 'en', pollIntervalMinutes: 360 },
  { name: 'FIFA', url: 'https://www.fifa.com', sourceType: 'website', catalogGroup: 'orgs-companies', sourceLanguage: 'en', pollIntervalMinutes: 360 },
  { name: 'AFC', url: 'https://www.the-afc.com', sourceType: 'website', catalogGroup: 'orgs-companies', sourceLanguage: 'en', pollIntervalMinutes: 360 },
  { name: 'دیجی‌کالا مگ', url: 'https://www.digikala.com/mag', sourceType: 'website', catalogGroup: 'orgs-companies', sourceLanguage: 'fa', pollIntervalMinutes: 360 },
  { name: 'اسنپ بلاگ', url: 'https://snapp.ir/blog', sourceType: 'website', catalogGroup: 'orgs-companies', sourceLanguage: 'fa', pollIntervalMinutes: 360 },
  { name: 'همراه اول', url: 'https://www.mci.ir', sourceType: 'website', catalogGroup: 'orgs-companies', sourceLanguage: 'fa', pollIntervalMinutes: 360 },
  { name: 'ایرانسل', url: 'https://www.irancell.ir', sourceType: 'website', catalogGroup: 'orgs-companies', sourceLanguage: 'fa', pollIntervalMinutes: 360 },
  { name: 'آپارات', url: 'https://www.aparat.com', sourceType: 'website', catalogGroup: 'orgs-companies', sourceLanguage: 'fa', pollIntervalMinutes: 360 },
  { name: 'کافه‌بازار بلاگ', url: 'https://blog.cafebazaar.ir', sourceType: 'website', catalogGroup: 'orgs-companies', sourceLanguage: 'fa', pollIntervalMinutes: 360 },
  { name: 'انجمن روابط عمومی ایران', url: 'https://www.priran.ir', sourceType: 'website', catalogGroup: 'orgs-companies', sourceLanguage: 'fa', pollIntervalMinutes: 360 },
  { name: 'حوزه هنری', url: 'https://www.hozehonari.ir', sourceType: 'website', catalogGroup: 'orgs-companies', sourceLanguage: 'fa', pollIntervalMinutes: 360 },
  { name: 'بنیاد ملی نخبگان', url: 'https://www.bmn.ir', sourceType: 'website', catalogGroup: 'orgs-companies', sourceLanguage: 'fa', pollIntervalMinutes: 360 },
];
